version: '3.8'

services:
  extractor:
    image: node:20
    volumes:
      - ./extractor:/app
      - ./snapshot:/home/node
    working_dir: /app
    command: node index.js
    ports:
      - "3003:3000"
  snapshotor:
    image: my-singlefile
    volumes:
      - ./snapshotor:/app
      - ./snapshot:/home/node
    working_dir: /app
    command: node index.js
    ports:
      - "3004:3000"