version: '3.8'

services:
  kimi-free-api:
    image: vinlic/kimi-free-api:latest
    restart: always
    ports:
      - "3002:8000"
    environment:
      - TZ=Asia/Shanghai
  extractor:
    image: node:20
    volumes:
      - ./extractor:/app
      - ./snapshot:/home/node
    working_dir: /app
    command: node index.js
    ports:
      - "3003:3000"
  snapshotor:
    container_name: singlefile
    image: screenbreak/singlefile-dockerized
    entrypoint: python3
    command: webserver.py
    volumes:
      - ./snapshotor:/opt/app
      - ./snapshot:/home/node
    ports:
      - "3004:80"
  main:
    image: openjdk:21-jdk-bullseye
    volumes:
      - ./target/bookmark-enhance-0.0.1-SNAPSHOT.tar.gz:/app/bookmark-enhance-0.0.1-SNAPSHOT.tar.gz
      - ./index:/app/bookmark-enhance-0.0.1-SNAPSHOT/index
      - ./snapshot:/app/bookmark-enhance-0.0.1-SNAPSHOT/snapshot
    working_dir: /app
    command: sh -c "tar -xzf bookmark-enhance-0.0.1-SNAPSHOT.tar.gz && cd bookmark-enhance-0.0.1-SNAPSHOT && java -Xmx2048m -jar bookmark-enhance-0.0.1-SNAPSHOT.jar"
    ports:
      - "18001:8082"