version: '3.8'

services:
  node_app:
    image: node:20
    volumes:
      - ./extractor:/app
      - ./snapshot:/home/node
    working_dir: /app
    command: node index.js
    ports:
      - "3003:3000"